### PR TITLE
Port upstream PRs

### PR DESCRIPTION
**Pull request by matheusd**
This is the first batch of upstream commits made since our last merge point. It includes the upstream PRs: 2454, 2445, 2289, 2430, 2452, 2431, 2446, 2462, 2275, 2397, 2471, 2198.

They mostly deal with bugfixes and refactorings for upcoming features.

The import paths and APIs in the individual commits were adjusted as needed. A few extra commits were done when the changes were significant enough.

This is currently rebased on top of a branch that includes all currently outstanding PRs, to facilitate later merging, so I'm leaving this as a draft PR until the older ones are reviewed, approved and merged.

### CODE REVIEW

**Comment by matheusd** [comment]
Updated up to upstream master as of 2019-07-08 (commit a6e77811 PR 3251).

**Comment by isuldor** [comment]
I've been running a dcrlnd build from this for the last few weeks with auotpilot enabled and had no issues (I'd provide build info but I'm currently remote)

**Comment by matheusd** [comment]
FYI, as of the end of July we're pretty much in sync with the upstream lnd master on my private branch.

I've checked up to commit https://github.com/lightningnetwork/lnd/commit/add905d17f7bbb11d0df2761cdf8accf2fef2b00 from upstream (PR 3346).

I've gone over 377 PRs since our branching point, with 1177 commits done from the original 1614 upstream commits.

**Comment by matheusd** [comment]
This has now been updated up to commit https://github.com/lightningnetwork/lnd/commit/d08721b32dcb942e896d48b4dad2742a37cc2118

My public test node is running this version. I'm also running a watchtower server at the following address, in case anyone wants to try it out:

`020afbc99d8d0e1052dfffdcd987c381bc349e20fc4b84e4839b3e1d01a1c954ae@207.246.122.217:9911`

Log from the tower for a breached channel:

```
2019-08-30 19:13:22.932 [INF] WTWR: Found 1 breach in (height=256232, hash=0000004d1b6a020ee25468d8ffde34749cbb82a8425ed73cc0cde73e59ca2360)   
2019-08-30 19:13:22.933 [INF] WTWR: Dispatching punisher for client 02a67b73678b9bd2729ec3c1738d6d3314c765e98d18fe09e49337320357115e4b, breach-
txid=373fac4e554e1b4c8a39573f65e7d3b121f2587be3af0b69728d5feb9f999b9f                                                                        
2019-08-30 19:13:22.935 [INF] WTWR: Publishing justice transaction for client=02a67b73678b9bd2729ec3c1738d6d3314c765e98d18fe09e49337320357115e4
b with txid=15fa1d56ed054aeed809e8cb84cda9046cc4ef2ad24203778f197233ac5f5f68                                                                   2019-08-30 19:13:23.003 [INF] WTWR: Punishment for client 02a67b73678b9bd2729ec3c1738d6d3314c765e98d18fe09e49337320357115e4b with breach-txid=3
73fac4e554e1b4c8a39573f65e7d3b121f2587be3af0b69728d5feb9f999b9f dispatched
```

**Pull request merged**
