### PR TITLE
lnrpc: add plugin in shell and fix others bug

### PR DESCRIPTION
**Pull request by Sarlor**
Add grpc gateway plugin and swagger plugin in shell, fix some others bugs

### CODE REVIEW

**Comment by xaur** [comment]
This might conflict with renaming done [elsewhere](https://github.com/davecgh/dcrlnd/commits/initial_port).

**Comment by Sarlor** [comment]
> This might conflict with renaming done [elsewhere](https://github.com/davecgh/dcrlnd/commits/initial_port).

Why ?

**Comment by xaur** [comment]
I just remember that some very similar renames were happening in that branch, although I didn't check exact lines.

**Comment by davecgh** [comment]
Thanks for the PR, but the work is being done on the initial_port branch of github.com/davecgh/dcrlnd.  This is against the master branch which contains none of the port work, so it would conflict.  The port work is also not yet ready for external contributors.  I don't know why the Decred org tweeted out about it yet, but that should not have been done.  Closing.

**Pull request closed without merging**
